Event map dev
mhendlich/localhost pull request #1
Opened 2021-12-21 23:35 UTC by e-mauss

Added shared prisma service, getAll route for events in the backend.
Implemented map page in the frontend.
Added necessary event dto.

2021-12-22 08:11 UTC, mhendlich requested changes

2021-12-22 08:11 UTC, mhendlich commented on packages/api/src/modules/event/event.service.ts
> +   constructor(private prisma: PrismaService) {}
es ist good practise die ganzen felder immer `private readonly` zu machen. in dem projekt ist ein vscode snippet dafür hinterlegt, einfach `prr` eintippen und autocompleten

2021-12-22 08:11 UTC, mhendlich commented on packages/web/pages/map.tsx
> +   const { isLoading, isError, data } = useQuery(
1. ist `data` schon sauber getyped wenn man die generics hier so angibt?
2. denke das url mappen mit `buildApiUrl` kann man auch direkt in die fetcher funktion packen, dann muss man das nicht jedes mal machen
3. Du gibst im endpunkt `/event` laut controller ein ganzes `Event` zurück, typest das aber hier als subset davon

2021-12-22 08:11 UTC, mhendlich commented on packages/web/package.json
> +    "react-map-gl": "^6.1.18",
ich glaub es braucht auch noch `@types/react-map-gl`, oder?

2021-12-22 08:11 UTC, mhendlich commented on packages/web/package.json
> +    "start": "next start --port 8000",
port für live-betrieb sollte aus einer umgebungsvariable gezogen werden, und ansonsten auf 8000 oder so defaulten. Kann man aber erstmal so lassen.

2021-12-22 11:44 UTC, e-mauss commented on packages/web/package.json
> +    "react-map-gl": "^6.1.18",
Hatte ich ursprünglich mit drin, läuft aber auch ohne. Hab die types bisher noch nicht gebraucht. Kanns trotzdem hinzufügen, wird schon nicht schaden. ^^

2021-12-22 12:07 UTC, mhendlich commented on packages/web/package.json
> +    "react-map-gl": "^6.1.18",
immer mit types

2021-12-22 13:29 UTC, e-mauss commented on packages/api/src/modules/event/event.service.ts
> +   constructor(private prisma: PrismaService) {}
Prisma service ist jetzt private readonly

Route um events zu createn hinzugefügt

2021-12-22 13:34 UTC, e-mauss commented on packages/web/pages/map.tsx
> +   const { isLoading, isError, data } = useQuery(
Data ist so schon sauber getyped. ^^
BuildApiUrl ist jetzt im fetcher mit drin.
Event Objects zwischen frontend und backend sind jetzt gesteamlined.

2021-12-22 13:34 UTC, e-mauss commented on packages/web/package.json
> +    "react-map-gl": "^6.1.18",
done :)

2021-12-22 13:34 UTC, e-mauss commented on packages/web/package.json
> +    "start": "next start --port 8000",
ich behalts im hinterkopf ^^

2021-12-23 10:05 UTC, mhendlich approved these changes

2021-12-23 10:05 UTC, merged