Dto impls
mhendlich/localhost pull request #11
Opened 2021-12-25 23:34 UTC by e-mauss

Impls for Dtos

2021-12-26 12:23 UTC, e-mauss commented on packages/api/src/modules/event/dto/event-upsert.dto-impl.ts
> +   @IsDate()
Die decorator die hier schon da sind kann man bestimmt auch noch mehr constraints enforcen lassen.

2021-12-26 14:44 UTC, e-mauss commented on packages/api/src/modules/event/dto/event-upsert.dto-impl.ts
> +   @IsDate()
Done

2021-12-26 14:45 UTC, e-mauss commented on packages/api/src/modules/event/event.service.ts
> +                           interest: {
Habs geändert, dass events nur noch zu bestehenden topics connecten. Ich glaube topics sind zu komplex um sie während dem event-create-process mit anzulegen (ui/ux-technisch)

2021-12-26 14:46 UTC, e-mauss commented on packages/api/src/modules/event/dto/event-upsert.dto-impl.ts
> +      description: string
Hat sich erledigt. Ist jetzt einfach eine topicIds string array.

2021-12-26 16:57 UTC, mhendlich requested changes

2021-12-26 16:57 UTC, mhendlich commented on packages/api/src/modules/event/dto/event-upsert.dto-impl.ts
> +   @IsDateString()
kannst eventuell auch mit dem `DayJsTransform` arbeiten den ich eingecheckt hab

2021-12-26 16:57 UTC, mhendlich commented on packages/api/src/modules/event/dto/event-upsert.dto-impl.ts
> +   @IsArray()
kannst du auch mit `@IsString({ each: true })` checken um arrays zu typen

2021-12-26 16:57 UTC, mhendlich commented on packages/api/src/modules/interest/interest.controller.ts
> +   create(@Body() dto: InterestUpsertDto): Promise<Interest> {
dto impl

2021-12-26 16:57 UTC, mhendlich commented on packages/api/src/modules/topic/topic.controller.ts
> +   create(@Body() dto: TopicUpsertDtoImpl): Promise<Topic> {
nur ne semantische kleinigkeit: DTO bezeichnet idR eher die spezifikation der transferierten daten und wäre hier als benennung der instanz nicht so korrekt. dann eher `body` oder `payload` oder so. ist aber nur ne kleinigkeit

2021-12-27 13:02 UTC, e-mauss commented on packages/api/src/modules/topic/topic.controller.ts
> +   create(@Body() dto: TopicUpsertDtoImpl): Promise<Topic> {
:+1:

2021-12-27 13:02 UTC, e-mauss commented on packages/api/src/modules/interest/interest.controller.ts
> +   create(@Body() dto: InterestUpsertDto): Promise<Interest> {
Ist geändert. ^^

2021-12-27 13:04 UTC, e-mauss commented on packages/api/src/modules/event/dto/event-upsert.dto-impl.ts
> +   @IsDateString()
Ich behalts im hinterkopf, ist hier aber glaub ich nicht ganz passend, weil ich das date eh nicht weiterverarbeite. Prisma kommt mit den dayjs objects nicht klar, deswegen wärs praktischer das einfach als datestring oder Date zu persisten

2021-12-27 13:09 UTC, mhendlich approved these changes

2021-12-27 13:09 UTC, merged