Added User Profile feature (WIP)
mhendlich/localhost pull request #14
Opened 2021-12-27 15:25 UTC by kseniashikh

1) Put all the User Profile APIs in User module (deleted User Profile module)
2) Added additional Interest Apis (for future use in User Profile)
3) Added UpdateUserDto and UserDto

2021-12-27 17:16 UTC, e-mauss requested changes

2021-12-27 17:16 UTC, e-mauss commented on prisma/migrations/20211221193511_/migration.sql
> +/*
Not sure ob wir zwei mal die gleiche migration im repo haben wollen. Ich glaub ich hatte das ja schon unter anderem Namen eingecheckt.

2021-12-27 17:16 UTC, e-mauss commented on packages/dtos/src/user/user.dto.ts
> +export type UserDto = Pick<
UserDto ist einfach ein ganzer User wenn ich das richtig sehe. Dafür braucht man dann eigentlich keinen Dto. :D

2021-12-27 17:16 UTC, e-mauss commented on packages/dtos/src/user/updateUser.dto.ts
> +export type UpdateUserDto = Pick<User, 'firstName' | 'imageUrl'>
Den kann man noch erweitern, wenn das irgendwann mal nötig ist. ^^
Kann mir gut vorstellen dass wir irgendwann mehr als nur den first name und das image updaten wollen. Aber ich denke das ist erstmal so in ordnung.

2021-12-27 17:16 UTC, e-mauss commented on packages/dtos/src/interest/interest.dto.ts
> +export type InterestDto = Pick<
Wenn ich das richtig sehe ist das einfach ein komplettes Interest. Dafür braucht man dann keinen Dto, sonder kann einfach ein Interest übers Netzwerk zurückgeben.

2021-12-27 17:16 UTC, e-mauss commented on packages/api/src/modules/user/user.service.ts
> +   async getAll(): Promise<User[]> {
Hier würde man nen Dto brauchen wenn ich mich nicht irre. Die userInterests müssen das User Object dann extenden.
Der Dto sähe dann wahrscheinlich so aus: 
export type userWithInterestsDto = Pick<User, 'relevante Fields'> & {userInterests: {interest: {name: string, id: string, usw}}[] }

2021-12-28 09:46 UTC, kseniashikh commented on packages/api/src/modules/interest/interest.controller.ts
> +      @Body() updateInterestDto: Prisma.InterestUpdateInput
Danke, habe es angepasst. Ich werde dein updsertDto verwenden, da mann nur Namen des Interests ändern soll (das ist ja auch für künftige Implementierungen)

2021-12-28 09:46 UTC, kseniashikh commented on prisma/migrations/20211221193511_/migration.sql
> +/*
Ja du hast Recht habe es gelöscht

2021-12-28 09:46 UTC, kseniashikh commented on packages/dtos/src/user/user.dto.ts
> +export type UserDto = Pick<
Ja richtig, ich habe aber User dto angepasst, da wir ein User ohne createdAt und UpdatedAt braucuhen und außerdem braucht man Interests. Später werden wir auch messages und user events brauchen, deswegen kann man das später noch erweitern :)
(das betrifft auch dein letzter Komment)

2021-12-28 09:46 UTC, kseniashikh commented on packages/dtos/src/user/updateUser.dto.ts
> +export type UpdateUserDto = Pick<User, 'firstName' | 'imageUrl'>
Ja, ich denke, wir müssen es erstmal so lassen :)

2021-12-28 09:46 UTC, kseniashikh commented on packages/dtos/src/interest/interest.dto.ts
> +export type InterestDto = Pick<
Ja,habe es gelöscht

2021-12-28 09:46 UTC, kseniashikh commented on packages/api/src/modules/user/user.service.ts
> +   async getAll(): Promise<User[]> {
Ich habe es auch angepasst, aber ich denke wir brauchen nur einen name von Interest

2021-12-28 16:33 UTC, e-mauss requested changes

2021-12-28 16:33 UTC, e-mauss commented on packages/dtos/src/user/user.dto.ts
> +export type UserDto = Pick<
Wofür wird das passwort gebraucht? :o

2021-12-29 08:13 UTC, kseniashikh commented on packages/dtos/src/user/user.dto.ts
> +export type UserDto = Pick<
Also, dieses Passwort wird für die Methode getByEmailAndPass() benutzt.
Ich kann dann ein anderes UserProfileDto erstellen, so dass wir Logik zwischen User Profile und User Auth verteilen. Dort werde ich keine Password ausgeben

2021-12-29 13:45 UTC, e-mauss approved these changes

2021-12-29 16:58 UTC, merged