[WIP] Feature/fe-userprofile: implementation of user profile pages
mhendlich/localhost pull request #17
Opened 2022-01-17 16:57 UTC by kseniashikh

**1. Created user-profile pages:**
index (user profile), update (update user profile form), public(for public view), event (to list user events), [id] (to view single event)
2. Implemented **basic routing and functionality of index and update page** (the rest are empty)
**3. Created Simple Banner**

2022-01-19 19:18 UTC, mhendlich requested changes

2022-01-19 19:18 UTC, mhendlich commented on packages/web/env.local
> +NEXT_PUBLIC_MAPBOX_API_ACCESS_TOKEN="pk.eyJ1IjoiZS1tYXVzcyIsImEiOiJja3hnanhrN2ExdDZvMm9wZHFyN2prNmozIn0.NpNRAKHFBJvDYu2fAA42jQ"
Datei bitte löschen

2022-01-19 19:18 UTC, mhendlich commented on packages/api/src/modules/user/user.service.ts
> +               deleteMany: {},
markiers das als TODO

2022-01-20 16:02 UTC, mhendlich approved these changes

2022-01-20 16:03 UTC, mhendlich commented
@KseniaShikhovtseva  Kann ich das mergen? Weil noch WIP im titel steht

2022-01-20 16:25 UTC, kseniashikh commented
@mhendlich ja, habe WIP weggenommen

2022-01-20 16:46 UTC, merged