[WIP] Map filter dev
mhendlich/localhost pull request #3
Opened 2021-12-23 13:37 UTC by e-mauss

Erste components, die ich (wahrscheinlich) im filter modal benutzen werde.

2021-12-24 20:43 UTC, mhendlich requested changes

2021-12-24 20:43 UTC, mhendlich commented on packages/web/components/chip-array.tsx
> +         {chipData.map(data => {
wenn du klammern um die brackets haust kannst du dir das return sparen

`data => ({
	<ListItem key={data.key}>
         	<Chip label={data.label} onDelete={handleDelete(data)} />
         </ListItem>
})
`

2021-12-24 20:43 UTC, mhendlich commented on packages/web/components/geolocation-button.tsx
> +         onClick={async () => {
würde funktionen die mehr als 2-3 zeilen lang sind immer ausm jsx extrahieren

2021-12-24 20:43 UTC, mhendlich commented on packages/web/components/map-filter.tsx
> +   const { showModal, hideModal, isVisible } = useModalState(false)
false ist default, kann man weglassen

2021-12-24 20:43 UTC, mhendlich commented on packages/web/components/map-filter.tsx
> +   const [unit, setUnit] = React.useState<string>('km')
versuch werte, die auch ein enum sein könnten aber hier ein string sind, als string union zu typen

2021-12-24 20:43 UTC, mhendlich commented on packages/web/components/map-filter.tsx
> +      const nextWeek = new Date(
für date operationen kann ich dayjs nur sehr empfehlen, hat ne viel angenehmere api

2021-12-24 20:43 UTC, mhendlich commented on packages/web/components/toggle-buttons-multiple.tsx
> +export enum Weekday {
hier auch lieber ei nstring union nehmen, enums braucht man eigentlich nie

2021-12-24 20:43 UTC, mhendlich commented on packages/web/pages/map.tsx
> +   const [filteredData, setFilteredData] = useState<Event[]>(data ? data : [])
kannst den term im der klammer auch als `data ?? []` schreiben

2021-12-24 23:35 UTC, e-mauss commented on packages/web/components/toggle-buttons-multiple.tsx
> +export enum Weekday {
Die enum ist hier tatsächlich praktisch weil die getDay funktion von nem Date object nen integer zwischen 0 und 6 zurückgibt, den man dann direkt mit den values von der enum vergleichen kann. Wenn das ein Problem ist das sich mit der API von dayjs löst dann move ich gern von der enum weg. :D

2021-12-24 23:36 UTC, e-mauss commented on packages/web/components/toggle-buttons-multiple.tsx
> +export enum Weekday {
Ich könnte natürlich auch ne integer union verwenden.

2021-12-24 23:50 UTC, e-mauss commented on packages/web/pages/map.tsx
> +   const [filteredData, setFilteredData] = useState<Event[]>(data ? data : [])
done

2021-12-24 23:52 UTC, e-mauss commented on packages/web/components/chip-array.tsx
> +export default function ChipArray() {
Hab alle Komponenten umgeschrieben. Und zwei unbenutzte Components entfernt. ^^

2021-12-24 23:53 UTC, e-mauss commented on packages/web/components/chip-array.tsx
> +         {chipData.map(data => {
Wurde entfernt.

2021-12-24 23:53 UTC, e-mauss commented on packages/web/components/geolocation-button.tsx
> +         onClick={async () => {
done

2021-12-24 23:54 UTC, e-mauss commented on packages/web/components/map-filter.tsx
> +   const { showModal, hideModal, isVisible } = useModalState(false)
done

2021-12-24 23:55 UTC, e-mauss commented on packages/web/components/map-filter.tsx
> +   const [unit, setUnit] = React.useState<string>('km')
Units hab ich entfernt weil eh nur km sinnvoll sind. Weekdays sind jetzt als integer union umgesetzt, weil das mit der dayjs api gut funktioniert. ^^

2021-12-24 23:55 UTC, e-mauss commented on packages/web/components/map-filter.tsx
> +      const nextWeek = new Date(
:+1:

2021-12-25 11:10 UTC, mhendlich approved these changes

2021-12-25 11:10 UTC, merged