[WIP] Map marker route
mhendlich/localhost pull request #5
Opened 2021-12-24 19:44 UTC by e-mauss

Neue Route, um Event data zu fetchen, die für MapMarker und den MapFilter relevant ist. EventMarkerDto hinzugefügt.

2021-12-24 20:44 UTC, mhendlich requested changes

2021-12-24 20:44 UTC, mhendlich commented on packages/dtos/src/event/event-marker.dto.ts
> +type EventTopic = {
kannst aus den 3 types auch eins machen, das zu nesten ist ok

2021-12-24 22:38 UTC, e-mauss commented on packages/dtos/src/event/event-marker.dto.ts
> +type EventTopic = {
done

2021-12-25 13:04 UTC, mhendlich approved these changes

2021-12-25 13:04 UTC, merged